# Generated by Django 4.2.7 on 2024-06-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retTuner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datasetsData',
            fields=[
                ('datasetID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('datasetName', models.CharField(max_length=100)),
                ('xCols', models.CharField(max_length=500)),
                ('yCols', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='hyperParametersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperParameterName', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.datasetsdata')),
            ],
        ),
        migrations.CreateModel(
            name='modelData',
            fields=[
                ('modelID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('modelName', models.CharField(max_length=100)),
                ('classPath', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('avgComplexity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='organizationData',
            fields=[
                ('organizationID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='preprocessMethodData',
            fields=[
                ('methodID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('avgComplexity', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usersdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='phone',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='userOrganizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.organizationdata')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.usersdata')),
            ],
        ),
        migrations.CreateModel(
            name='preprocessedByData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arguments', models.TextField()),
                ('datasetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.datasetsdata')),
                ('methodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.preprocessmethoddata')),
            ],
        ),
        migrations.CreateModel(
            name='obtainsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('datasetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.datasetsdata')),
                ('hyperParameterName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.hyperparametersdata')),
                ('methodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.preprocessmethoddata')),
            ],
        ),
        migrations.CreateModel(
            name='metaFeaturesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfInstances', models.IntegerField()),
                ('logNumberOfInstances', models.FloatField()),
                ('logNumberOfFeatures', models.FloatField()),
                ('numberOfClasses', models.IntegerField()),
                ('numberOfCategoricalFeatures', models.IntegerField()),
                ('numberOfNumericalFeatures', models.IntegerField()),
                ('ratioOfNumericFeatures', models.FloatField()),
                ('ratioOfCategoricalFeatures', models.FloatField()),
                ('classEntropy', models.FloatField()),
                ('classProbability', models.FloatField()),
                ('symbolsMean', models.FloatField()),
                ('skewnessMean', models.FloatField()),
                ('kurtosisMean', models.FloatField()),
                ('datasetRatio', models.FloatField()),
                ('datasetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.datasetsdata')),
            ],
        ),
        migrations.CreateModel(
            name='evaluationStrategyData',
            fields=[
                ('stratiID', models.IntegerField(primary_key=True, serialize=False)),
                ('stratName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reliableThreshold', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('avgComplexity', models.FloatField()),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.modeldata')),
            ],
        ),
        migrations.CreateModel(
            name='evaluationScoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stratiID', models.IntegerField()),
                ('score', models.FloatField()),
                ('datasetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.datasetsdata')),
            ],
        ),
        migrations.AddField(
            model_name='datasetsdata',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retTuner.usersdata'),
        ),
    ]
