# Generated by Django 4.2.7 on 2024-07-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retTuner', '0003_rename_modelid_hyperparametersdata_datasetid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetsdata',
            old_name='userID',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='userorganizationdata',
            old_name='userID',
            new_name='phone',
        ),
    ]
