# Generated by Django 4.2.7 on 2024-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retTuner', '0004_rename_userid_datasetsdata_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetsdata',
            old_name='organization',
            new_name='modelname',
        ),
        migrations.RenameField(
            model_name='datasetsdata',
            old_name='size',
            new_name='problemType',
        ),
        migrations.RemoveField(
            model_name='datasetsdata',
            name='path',
        ),
        migrations.RemoveField(
            model_name='datasetsdata',
            name='xCols',
        ),
        migrations.RemoveField(
            model_name='datasetsdata',
            name='yCols',
        ),
        migrations.AddField(
            model_name='datasetsdata',
            name='date',
            field=models.DateField(default='2020-06-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetsdata',
            name='description',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetsdata',
            name='responseVariable',
            field=models.CharField(default='lol', max_length=100),
            preserve_default=False,
        ),
    ]
