# Generated by Django 4.2.7 on 2024-07-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retTuner', '0007_datasetsdata_modelaccuracy_datasetsdata_modelmse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsdata',
            name='modelaccuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datasetsdata',
            name='modelmse',
            field=models.FloatField(null=True),
        ),
    ]
